nama = input("Nama : ")
nim = input("NIM : ")
kelas_paralel = input("Kelas Paralel : ")
tempat_lahir = input("Tempat Lahir : ")
tanggal_lahir = input("Tanggal Lahir (dd-mm-yyyy) : ")
alamat = input("Alamat : ")
hobby = input("Hobby : ")
no_hp = input("No. HP : ")
print("Nama : " + nama)
print("NIM : " + nim)
print("Kelas Paralel : " + kelas_paralel)
print("Tempat/Tanggal Lahir : " + tempat_lahir + "/" + tanggal_lahir)
print("Alamat : " + alamat)
print("Hobby : " + hobby)
print("No. HP : " + no_hp)